Спринт 7: Добавить новую реализацию интерфейса TaskManagers, которая …
savel11/java-kanban pull request #2
Opened 2024-07-22 17:10 UTC by savel11

…сохраняет задачи в файл. Добавить тесты к новому классу

2024-07-23 17:54 UTC, sergeymamonov requested changes

2024-07-23 17:54 UTC, sergeymamonov commented on fileForTest12109203018695476795.txt
> +id,type,name,status,description,epic
Сейчас в проекте беспорядок. Если эти тестовые файлы нужны для тестов, то их нужно положить в папку resouce в папке test.

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
> +            fileWriter.write("id,type,name,status,description,epic");
Литералы лучше выносить из кода в константы с информативными названиями.

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
> +            stringTask = String.format("%d,%s,%s,%s,%s", task.getId(), TypeClass.TASK, task.getNameTask(), task.getStatus(), task.getDescriptionTask());
Старайтесь не выходить за лимит в 120 символов в строке и при необходимости переносить на следующую строку.

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
> +            stringTask = String.format("%d,%s,%s,%s,%s,%d", task.getId(), TypeClass.SUBTASK, task.getNameTask(), task.getStatus(), task.getDescriptionTask(), task.getEpic().getId());
Еще можно с помощью метоад String.join

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/InMemoryTaskManager.java
>      HistoryManager inMemoryHistoryManager = Managers.getDefaultHistory();
Здесь используется модификатор доступа по умолчанию или просто пропущен?

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/Managers.java
> +        return inMemoryHistoryManager;
В этом классе создаются два менеджера один объект класса, второй статический. Лучше inMemoryHistoryManager не создавать статическим полем, а создавать внутри getDefaultHistory. Если будут сложности, то обратитесь к наставнику.

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/TaskManager.java
А где используется метод getSubtasksForEpic?

2024-07-23 17:54 UTC, sergeymamonov commented on src/manager/TaskManager.java
deleteTaskForId. Обычно называют ...ById

2024-07-24 17:56 UTC, savel11 commented on src/manager/TaskManager.java
Метод может быть использован пользователям, чтобы просмотреть все подзадачи определенного эпика. В одном из тз было написано реализовать, данный метод

2024-07-24 20:52 UTC, sergeymamonov approved these changes

2024-07-24 20:52 UTC, sergeymamonov commented on savedTasks.txt
> +id,type,name,status,description,epic
папка src - это корневая папка. В ней есть папка с тестами. Если это сгенерированный пробный файл, то его не должно быть в репозитории. Можно настроить фаил гитигнор, чтобы текстовые файлы *.txt не попадали в коммиты. Либо при коммите указывать нужные файлы, а не нужные не указывать. Если что, спрашивайте что непонятно у наставника.

2024-08-02 13:53 UTC, merged