Sprint 9 solution http api
savel11/java-kanban pull request #4
Opened 2024-08-25 17:07 UTC by savel11

2024-08-25 19:42 UTC, sergeymamonov requested changes

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
> +    public static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("HH.mm.dd.MM.yy");
Можно сделать приватным, так как используется только в этом классе.

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
>      public String getNameClass(String str) {
default -> "Epic"; - так опасно делать. Если добавится новый статус, то ошибки здесь не возникнет, но вместо нового статуса вы будет делать эпик. Нужно явно прописать для эпика, а неизвестный должен идти в default и там уже можно кинуть ошибку, например.
Для статуса анологично.

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
>                  if (fileBackedTaskManager.getNameClass(line).equals("Task")) {
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.
"Task".equal(...
Посмотрите по всему проекту.

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/InMemoryTaskManager.java
> +        if (task1.getStartTime().equals(task2.getStartTime())) {
Попробуйте написать компаратор через comparing() - так будет нагляднее и короче.

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/InMemoryTaskManager.java
>      }
Если геттер не нужен, то удалите его.

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/InMemoryTaskManager.java
> +        if (tasks.containsKey(id)) {
Лучше стараться чтобы код был ближе к левой стороне. Если можно обойтись без сдвигания его вправо, то лучше этого не делать. В данной ситуации можно if (!tasks.containsKey(id)) {throw new NotFoundException();}
А дальше уже код метод без сдига вправо. Потому что когда кода станет больше он будет сильно уходить вправо и читать его станет сложнее. Плюс в данной ситуации мы применили подход fail fast - как можно раньше выходить из метода, если входные аргументы не удовлетворяют требованиям.
Ниже в методах можно тоже применять аналогичные подходы.

2024-08-25 19:42 UTC, sergeymamonov commented on src/manager/NotFoundException.java
> +    public NotFoundException() {
При такой ошибке сложно понять, какой именно случай привел к ошибке. Обычно в ошибке пишут информативный текст и передают в нее необходимые аргументы, например Task with id = %s not found

2024-08-25 19:42 UTC, sergeymamonov commented on src/model/Epic.java
> +                streamSupplier.get().min((Subtask subtask1, Subtask subtask2) -> {
Попробуйте через comparing()

2024-08-25 19:42 UTC, sergeymamonov commented on src/model/Task.java
> +    public static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm dd.MM.yy");
Эта константа встречается в проекте два раза. Лучше оставить одну.

2024-08-25 19:42 UTC, sergeymamonov commented on src/model/Task.java
>      protected TaskStatus status;
Почему именно к этому полю нельзя обратиться через геттер и сеттер? Я бы поменял на private, если нет причин для такого модификатора, как сейчас.

2024-08-25 19:42 UTC, sergeymamonov commented on src/server/BaseHttpHandler.java
> +        if ((pathParts[1].equals("tasks") || pathParts[1].equals("subtasks")
Если pathParts[1] == null, то здесь и в аналогичных местах будет NPE.

2024-08-25 19:42 UTC, sergeymamonov commented on src/server/DurationAdapter.java
> +package server;
Какое отношение этот класс имеет к пакету, который называется server. Пересмотрите распределение классов по пакетам.

2024-08-25 19:42 UTC, sergeymamonov commented on test/HttpTaskManagerEpicsTest.java
> +class ServerEpicsTypeToken extends TypeToken<ArrayList<Epic>> {
Не очень понял, зачем этот класс добавлен в некоторые тестовые классы. Если этот класс вам нужен, то сделайте его как это принято в Java в виде отдельного файла.

2024-08-26 05:13 UTC, savel11 commented on src/manager/NotFoundException.java
> +    public NotFoundException() {
Данная ошибка обрабатывается при запросах, и если задача не найдено то пользователю выдается код 404 вместе с ответом: "Задача с идентификатором " + id + " не найдена"

2024-08-26 18:48 UTC, sergeymamonov approved these changes

2024-08-26 18:48 UTC, sergeymamonov commented on src/manager/FileBackedTaskManager.java
> +            default -> throw new NotFoundException("Неизвестный статус задачи");
Я бы назвал IllegalTaskType, IllegalTaskStatus.

2024-08-26 18:48 UTC, sergeymamonov commented on src/typetokens/SubtasksTypeToken.java
> +public class SubtasksTypeToken extends TypeToken<ArrayList<Subtask>> {
Для чего нужен этот класс? Если только для тестов, то почему он не в папке test?

2024-09-15 10:03 UTC, merged